# Generated by Django 4.1.4 on 2023-02-22 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback_alter_mynotes_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 23, 2, 287813))),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 23, 2, 288812)),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 23, 2, 288812)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 23, 2, 288812)),
        ),
    ]
