# Generated by Django 4.1.4 on 2023-02-22 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_adminregister_alter_feedback_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregister',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 29, 58, 825215)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 29, 58, 826215)),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 29, 58, 826215)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 11, 29, 58, 825215)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
